import { HashMap } from "./HashMap.js"
import { HashSet } from "./HashSet.js"

const content = document.getElementById("content")
const test = new HashMap()
const testSet = new HashSet()

test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
console.log(test.entries())
console.log(test.keys())
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
console.log(test.entries())
console.log(test.keys())
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
console.log(test.entries())
console.log(test.keys())
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')

console.log(test.entries())
console.log(test.length())
console.log(test.keys())

console.log("Add more")
test.set('moon', 'silver')
console.log(test.entries())
console.log(test.keys())

console.log("Again more")
test.set('hawkeye', 'Clint Barton')
console.log(test.entries())
console.log(test.keys())

console.log("Again more 2")
test.set('wonderwoman', 'Diana Prince')
console.log(test.entries())
console.log(test.keys())

console.log("Again more 3")
test.set('hulk', 'Bruce Banner')
console.log(test.entries())
console.log(test.keys())

console.log("=================================")
console.log("Again more 4")
test.set('blackwidow', 'Natasha Romanoff')
console.log(test.get("blackwidow"))
console.log(test.entries())

console.log("Again more 5")
test.set('blackwidow', 'Yelena Belova')
console.log(test.get("blackwidow"))
console.log(test.entries())
console.log("=================================")
console.log(test.length())
console.log(test.keys())

console.log("Again more 6")
test.set('superman', 'Clark Kent')
console.log("Again more 7")
test.set('batman', 'Bruce Wayne')
console.log(test.length())
console.log(test.entries())
console.log(test.keys())

// console.log(test.get("apple"))
// console.log(test.has("dog"))
// console.log(test.remove("grape"))

// console.log(test.entries())
// console.log(test.length())
// console.log(test.keys())

// console.log("HashSet")

// testSet.set('apple', 'red')
// testSet.set('banana', 'yellow')
// testSet.set('carrot', 'orange')
// testSet.set('dog', 'brown')
// testSet.set('elephant', 'gray')
// testSet.set('frog', 'green')
// testSet.set('grape', 'purple')
// testSet.set('hat', 'black')
// testSet.set('ice cream', 'white')
// testSet.set('jacket', 'blue')
// testSet.set('kite', 'pink')
// testSet.set('lion', 'golden')

// console.log(testSet.length())
// console.log(testSet.keys())

// console.log(testSet.has("dog"))
// console.log(testSet.remove("grape"))
